name: Build and publish multi-arch Docker images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Login to GHCR ---
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Login to Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Get VAR's ---
      - name: Set variables
        id: vars
        run: |
          echo "BUILDTIME=$(date)" >> $GITHUB_OUTPUT
          echo "VERSION=v1.19.15" >> $GITHUB_OUTPUT

      # --- Build mihomo AMD64_v1---
      - name: Build and push mihomo
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            TAG=${{ steps.vars.outputs.VERSION }}
            BUILDTIME=${{ steps.vars.outputs.BUILDTIME }}
            AMD64VERSION=v1
          tags: |
            ghcr.io/medium1992/mihomo-fakeip-ros:${{ steps.vars.outputs.VERSION }}-amd64_v1
            medium1992/mihomo-fakeip-ros:${{ steps.vars.outputs.VERSION }}-amd64_v1
            
      # --- Build mihomo AMD64_v2---
      - name: Build and push mihomo
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            TAG=${{ steps.vars.outputs.VERSION }}
            BUILDTIME=${{ steps.vars.outputs.BUILDTIME }}
            AMD64VERSION=v2
          tags: |
            ghcr.io/medium1992/mihomo-fakeip-ros:${{ steps.vars.outputs.VERSION }}-amd64_v2
            medium1992/mihomo-fakeip-ros:${{ steps.vars.outputs.VERSION }}-amd64_v2
                        
      # --- Build mihomo AMD64_v3, ARM64, ARM---
      - name: Build and push mihomo
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            TAG=${{ steps.vars.outputs.VERSION }}
            BUILDTIME=${{ steps.vars.outputs.BUILDTIME }}
            AMD64VERSION=v3
          tags: |
            ghcr.io/medium1992/mihomo-fakeip-ros:latest
            ghcr.io/medium1992/mihomo-fakeip-ros:${{ steps.vars.outputs.VERSION }}
            medium1992/mihomo-fakeip-ros:latest
            medium1992/mihomo-fakeip-ros:${{ steps.vars.outputs.VERSION }}
